apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32000 